OmnivusMvcWebsite/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace OmnivusMvcWebsite.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OmnivusMvcWebsite/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace OmnivusMvcWebsite.Controllers
{
    public class ServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OmnivusMvcWebsite/Views/Shared/_ContactContentPartial.cshtml
<div id="contactContent">
    <div id="contactContainer" class="container">
        <div id="contactForm">
            <div class="contentHeading">
                <p>About Us </p>
                <div class="contentHr"><p>some spa</p></div>
            </div>
            <h1>Estimate for your <br>projects.</h1>
            <div id="form">
                <input type="text" placeholder="Enter Your name" class="inputContainer" />
                <input type="text" placeholder="Enter Your name" class="inputContainer" />
                <textarea placeholder="Enter your message" class="mt-2"></textarea>
                <div class="contentBtns"><button class="learnBtn">Submit Now</button></div>

            </div>
        </div>

        <div id="contactImage">
            <img src="img/contact-img.svg" alt="contact-image.svg" />
        </div>
    </div>
</div>

OmnivusMvcWebsite/Views/Shared/_FooterPartial.cshtml
<section id="footer">
    <div class="footerContainer container">
        <div class="footerText">
            <h1>OmniVus.</h1>
            <p>
                The web has changed a lot since we posted our first article back in 2007. The team at Mattin-Lassi Group has changed too, as have the things that we bring to our community
                conferences, books, and our membership added to the online magazine.
                <br><br>
                One thing that hasn’t changed is that we’re a small team — with most of us not working
            </p>
        </div>
        <div class="footerWorkingHours">
            <h1>Working Hours</h1>
            <p class="dayHours">
                Monday - Friday: 7:00 - 17:00<br>
                Saturday: 7:00 - 12:00<br>
                Sunday and holidays: 8:00 - 10:00
            </p>
            <p><span>For more then 15 years,</span> IT Service has been a reliable partner in the field of logistics and cargo forwarding.</p>
        </div>
        <div class="copyright">
            <p>Copyright © Mattin-Lassei Group AB - 2022</p>
        </div>
    </div>

    <div id="footerBigC">
        <img src="/img/footer-big-circle.svg" alt="footer-big-c.svg" />
    </div>
    <div id="footerSmallC">
        <img src="/img/footer-small-circles.svg" alt="footer-small-c.svg" />
    </div>
</section>

OmnivusMvcWebsite/Views/Shared/_HeaderPartial.cshtml
<div class="container header">
    <!--Header-->
    <div class="logo">
        <!--Logo-->
        <img src="./img/logo.png" alt="logo.png" class="logo" />
    </div>
    <div class="container navbar-brand">
        <!--Navigations-->
        <div class="social-nav d-flex">
            <!--Socials-->

            @if (SignInManager.IsSignedIn(User))
            {
                <div id="infoemail">
                    <span>Welcome <a asp-controller="Profile" asp-action="Index" asp-route-id="@User.FindFirst("UserId").Value">@await ProfileManager.DisplayNameAsync(User.FindFirst("UserId").Value)</a></span>
                </div>
                <div class="socials">
                    @if(User.IsInRole("Admin"))
                    {
                        <div class="d-flex">
                            <a asp-controller="Admin" asp-action="Index" asp-route-id="@User.FindFirst("UserId").Value">Admin control</a>
                            <a asp-controller="auth" asp-action="SignOut">Sign Out</a>
                        </div>
                    }
                    else
                    {
                        <a asp-controller="auth" asp-action="SignOut">Sign Out</a>
                    }
                    
                </div>
            }
            else
            {
                <div id="infoemail">
                    <a href="#">info@domain.com</a>
                </div>
                <div class="socials">
                    <a href="#">facebook</a>
                    <a href="#">twitter</a>
                    <a href="#">linkedIn</a>
                    <a href="#">youtube</a>
                </div>
            }
 
        </div>
        <div class="bottomBorder mt-2"></div>

        <div class="navbar mt-5 d-flex flx-hrz-end flx-vrcl-center">
            <!--Navbar-->
            <a asp-controller="Home" asp-action="Index">Home</a>
            <a asp-controller="Service" asp-action="Index">Services</a>
            <a asp-controller="Contact" asp-action="Index">Contact</a>
            @if (!SignInManager.IsSignedIn(User))
            {
                <a asp-controller="auth" asp-action="SignIn"><button>Sign In</button></a>
            }
        </div>
    </div>
</div>

OmnivusMvcWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Omnivus</title>
    <link rel="stylesheet" href="~/css/style.min.css" asp-append-version="true" />
</head>
<body>
      
        @RenderBody()
        <partial name="_FooterPartial"/>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OmnivusMvcWebsite/Views/Shared/_PageTitlePartial.cshtml
<div id="page-title">
    <div id="servicesHtml">
            <div class="showcase container"><!--Showcase-->
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="links">
                <a asp-controller="Home" asp-action="Index">Home</a> 
                | 
                <a asp-controller="@ViewData["Title"]" asp-action="Index">@ViewData["Title"]</a>
            </div>
        </div>
</div>

OmnivusMvcWebsite/Views/Shared/_ServiceBoxPartial.cshtml
@model ServiceBoxModel

<div class="serviceBox">
    <div class="boxFooter">
        <div class="blueBox"></div>
        <p>@Model.Title</p>
        <p class="desc">@Model.Description</p>
    </div>
</div>

OmnivusMvcWebsite/Views/Shared/_ServiceContentPartial.cshtml
@{
   var UIUXDesign = new ServiceBoxModel {Title = "UI/UX Design", Description = "The functional goal of technical content is to help people use a product successfully. The business goal must tie the content."};
   var ITConsultancy = new ServiceBoxModel {Title = "IT Consultancy", Description = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC."};
   var TechnologyProf = new ServiceBoxModel {Title = "Technology Prof.", Description = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour."};
   var WebDevelopment = new ServiceBoxModel {Title = "Web Development", Description = "In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best."};
   var AppDevelopment = new ServiceBoxModel {Title = "App Development", Description = "Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain."};
   var GameDesign = new ServiceBoxModel {Title = "Game Design", Description = "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam."};

}


<div id="serviceContent">
    <div class="serviceGrid">
        <partial name="_ServiceBoxPartial" model="@UIUXDesign"/>
        <partial name="_ServiceBoxPartial" model="@ITConsultancy"/>
        <partial name="_ServiceBoxPartial" model="@TechnologyProf"/>
        <partial name="_ServiceBoxPartial" model="@WebDevelopment"/>
        <partial name="_ServiceBoxPartial" model="@AppDevelopment"/>
        <partial name="_ServiceBoxPartial" model="@GameDesign"/>
    </div>
</div>

OmnivusMvcWebsite/Views/Shared/_emptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Denied</title>
    <link rel="stylesheet" href="~/css/css/style.min.css" asp-append-version="true" />
</head>
<body>
      
        @RenderBody()


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OmnivusMvcWebsite/Views/Shared/_profileLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/style.min.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/3bf7119786.js"
            crossorigin="anonymous"></script>
</head>
<body>

    @RenderBody()


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @RenderSection("scipts", required: false)
</body>
</html>